apiVersion: v1
kind: ConfigMap
metadata:
  name: digital-signature-config
data:
  SPRING_PROFILES_ACTIVE: "prod"
  SERVER_PORT: "8080"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  RABBITMQ_VIRTUAL_HOST: "/"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "signature_db"
  VAULT_HOST: "vault-service"
  VAULT_PORT: "8200"
  VAULT_SCHEME: "http" 