apiVersion: v1
kind: Secret
metadata:
  name: digital-signature-secrets
type: Opaque
data:
  # Ces valeurs sont encodées en base64 et doivent être changées en production
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cGFzc3dvcmQ=  # password
  RABBITMQ_USERNAME: Z3Vlc3Q=  # guest
  RABBITMQ_PASSWORD: Z3Vlc3Q=  # guest
  VAULT_TOKEN: cm9vdC10b2tlbg==  # root-token 